# Generated by Django 5.2.5 on 2025-08-19 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='Users',
        ),
    ]
