# Generated by Django 5.2.5 on 2025-08-21 00:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0002_alter_stock_facilitator_alter_stock_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, editable=False, help_text='Date of the routine entry')),
                ('mortality', models.PositiveIntegerField(default=0, help_text='Number of deaths recorded (default: 0)')),
                ('age', models.PositiveIntegerField(default=0, editable=False)),
                ('feed_type', models.CharField(blank=True, choices=[('pellet', 'Pellet'), ('mash', 'Mash'), ('crumble', 'Crumble')], help_text='The type of feed given', max_length=50)),
                ('morning_feed', models.PositiveIntegerField(default=0, help_text='Number of 20-liter containers of feed in the morning')),
                ('evening_feed', models.PositiveIntegerField(default=0, help_text='Number of 20-liter containers of feed in the evening')),
                ('morning_water', models.PositiveBigIntegerField(help_text='Water given in liters (ltrs) in the morning')),
                ('evening_water', models.PositiveBigIntegerField(help_text='Water given in liters (ltrs) in the evening')),
                ('morning_medication', models.CharField(blank=True, help_text='Names of medication administered in the morning', max_length=100)),
                ('evening_medication', models.CharField(blank=True, help_text='Names of medication administered in the evening', max_length=100)),
                ('comment', models.TextField(blank=True, help_text='Additional notes or observations')),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_routines', to='stock.stock', to_field='batch_id')),
            ],
            options={
                'verbose_name': 'Daily Routine',
                'verbose_name_plural': 'Daily Routines',
                'unique_together': {('batch_id', 'date')},
            },
        ),
    ]
