# Generated by Django 5.2.5 on 2025-08-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_routine', '0001_initial'),
        ('stock', '0004_alter_stock_quantity_stocked_alter_stock_unit_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyroutine',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='dailyroutine',
            constraint=models.UniqueConstraint(fields=('batch_id', 'date'), name='unique_batch_id_date'),
        ),
    ]
