# Generated by Django 4.2 on 2025-08-25 07:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daily_routine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyroutine',
            name='date',
            field=models.DateField(editable=False, help_text='Date of the routine entry', verbose_name=django.utils.timezone.now),
        ),
    ]
