# Generated by Django 4.2 on 2025-08-25 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daily_routine', '0002_alter_dailyroutine_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyroutine',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, editable=False, help_text='Date of the routine entry'),
        ),
    ]
