# Generated by Django 5.2.5 on 2025-08-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_stocked', models.DateField(auto_now_add=True, help_text='Date the stock was added')),
                ('batch_id', models.CharField(help_text='Unique identifier for the batch', max_length=50, unique=True)),
                ('category', models.CharField(choices=[('poultry', 'Poultry'), ('fish', 'Fish'), ('goat', 'Goat')], default='poultry', help_text='Category of livestock', max_length=50)),
                ('breed', models.CharField(choices=[('broiler', 'Broiler'), ('noiler', 'Noiler'), ('clarias', 'Clarias'), ('hybrid', 'Hybrid')], default='broiler', help_text='Breed of the stock', max_length=20)),
                ('stock_type', models.CharField(choices=[('day_old_chick', 'Day-Old Chick'), ('fingerling', 'Fingerling'), ('juvenile', 'Juvenile'), ('grower', 'Grower'), ('adult_broiler', 'Adult Broiler'), ('point_of_lay', 'Point of Lay')], help_text='Life stage of the stock', max_length=20)),
                ('quantity_stocked', models.PositiveIntegerField(default=0, help_text='Initial quantity stocked')),
                ('total_mortality', models.PositiveIntegerField(default=0, help_text='Total deaths recorded')),
                ('total_sold', models.PositiveIntegerField(default=0, help_text='Total quantity sold')),
                ('supplier', models.CharField(help_text='Name of the supplier', max_length=50)),
                ('facilitator', models.CharField(help_text='Name of the facilitator', max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit in currency', max_digits=10)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, help_text='Total income from sales', max_digits=12)),
                ('total_expenditure', models.DecimalField(decimal_places=2, default=0, help_text='Total expenditure', max_digits=12)),
                ('reports', models.JSONField(blank=True, default=dict, help_text='Weekly reports in JSON format')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
    ]
