# Generated by Django 5.2.5 on 2025-08-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='facilitator',
            field=models.CharField(blank=True, help_text='Name of the facilitator', max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='supplier',
            field=models.CharField(blank=True, help_text='Name of the supplier', max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='total_mortality',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Total deaths recorded'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per unit in currency', max_digits=10),
        ),
    ]
