# Generated by Django 5.2.5 on 2025-08-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stock_facilitator_alter_stock_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity_stocked',
            field=models.PositiveIntegerField(default=0, help_text='Initial quantity stocked', verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='total_mortality',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Total deaths recorded', verbose_name='Mortality'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='total_sold',
            field=models.PositiveIntegerField(default=0, help_text='Total quantity sold', verbose_name='Sold'),
        ),
    ]
