# Generated by Django 5.2.5 on 2025-08-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stock_total_cost_alter_stock_quantity_stocked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity_stocked',
            field=models.PositiveIntegerField(help_text='Initial quantity stocked', verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit in currency', max_digits=10),
        ),
    ]
