# Generated by Django 4.2 on 2025-08-27 00:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(error_messages='Item name or title is mandory', max_length=50, verbose_name='Item Name/Title')),
                ('quantity', models.IntegerField(error_messages='Provide the quantity')),
                ('unit_cost', models.DecimalField(decimal_places=2, error_messages='Per unit cost is required', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Any infomation regarding this item?')),
                ('date_purchased', models.DateField(default=django.utils.timezone.now)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_expenditure', to='stock.stock')),
            ],
        ),
    ]
