# Generated by Django 4.2 on 2025-08-27 00:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('expenditure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenditure',
            options={'ordering': ['-date_purchased', 'item'], 'verbose_name': 'Expenditure', 'verbose_name_plural': 'Expenditures'},
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='date_purchased',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Purchased'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='description',
            field=models.TextField(blank=True, help_text='Any information regarding this item?', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='item',
            field=models.CharField(max_length=50, verbose_name='Item Name/Title'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Quantity must be at least 1.')], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='stock.stock', verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1, message='Unit cost cannot be zero or negative.')], verbose_name='Unit Cost'),
        ),
    ]
