# Generated by Django 4.2 on 2025-08-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0002_alter_expenditure_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='seller',
            field=models.CharField(blank=True, help_text='Name of the seller, store, or person paid for this expenditure.', max_length=100, verbose_name='Seller/Store'),
        ),
    ]
