# Generated by Django 4.2 on 2025-08-27 01:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0004_expenditure_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Ref Code'),
        ),
    ]
