# Generated by Django 5.2.5 on 2025-08-15 21:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_title', models.CharField(help_text='Name of the expense category (e.g., Office Supplies, Transport, Rent).', max_length=250, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description of this expense type.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this expense type is active and available for use.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expense Type',
                'verbose_name_plural': 'Expense Types',
                'ordering': ['expense_title'],
            },
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=250)),
                ('supplier', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now)),
                ('expense_type', models.ForeignKey(help_text='Select the category for this expense.', on_delete=django.db.models.deletion.PROTECT, related_name='expenditures', to='expenditure.expensetype')),
            ],
        ),
    ]
