# Generated by Django 5.2.5 on 2025-08-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensetype',
            options={'ordering': ['expense_title']},
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='expense_title',
            field=models.CharField(help_text='Name of the expense category (e.g., Office Supplies, Transport, Rent).', max_length=250),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
