# Generated by Django 5.2.5 on 2025-08-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0002_alter_expensetype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
