# Generated by Django 5.2.5 on 2025-08-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('mortality', models.IntegerField()),
                ('time_period', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='morning', max_length=100)),
                ('feeding', models.IntegerField()),
                ('drinking', models.IntegerField()),
                ('medication', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
