# Generated by Django 4.2 on 2025-08-27 06:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.CharField(choices=[('bird', 'Bird'), ('fish', 'Fish')], default='bird', help_text='What product type?', max_length=20, verbose_name='Product')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Cannot be zero or negative.')])),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1, 'Cannot be zero or negative')])),
                ('customer', models.CharField(blank=True, max_length=50)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('ongooing', 'Ongoing')], default='pending', max_length=20)),
                ('payment_mode', models.CharField(blank=True, choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('dual', 'Cash & Transfer')], max_length=20)),
                ('commenced_on', models.DateField(default=django.utils.timezone.now)),
                ('completed_on', models.DateField(blank=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_incomes', to='stock.stock')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
