# Generated by Django 4.2 on 2025-08-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='completed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='customer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('dual', 'Cash & Transfer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='product',
            field=models.CharField(choices=[('bird', 'Bird'), ('fish', 'Fish')], help_text='What product type?', max_length=20, verbose_name='Product'),
        ),
    ]
