# Generated by Django 4.2 on 2025-08-27 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_alter_income_completed_on_alter_income_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='customer',
            field=models.CharField(blank=True, help_text='Who buys this product?', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('dual', 'Cash & Transfer')], help_text='What is the payment method used?', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Total number of items', validators=[django.core.validators.MinValueValidator(1, 'Cannot be zero or negative.')]),
        ),
        migrations.AlterField(
            model_name='income',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Per item price', max_digits=10, validators=[django.core.validators.MinValueValidator(1, 'Cannot be zero or negative')]),
        ),
        migrations.AlterField(
            model_name='income',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='total weight in KG', max_digits=10),
        ),
    ]
