# Generated by Django 4.2 on 2025-08-27 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_alter_income_customer_alter_income_payment_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='quantity',
            field=models.IntegerField(help_text='Total number of items', validators=[django.core.validators.MinValueValidator(1, 'Cannot be zero or negative.')]),
        ),
    ]
